# Generated by Django 5.2.10 on 2026-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="added_by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest_name",
            field=models.CharField(max_length=255),
        ),
    ]
