# Generated by Django 5.2.10 on 2026-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0002_reservation_added_by_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_present",
            field=models.BooleanField(default=False),
        ),
    ]
