# Generated by Django 5.2.10 on 2026-01-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0003_reservation_is_present"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of passengers"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cars",
                "ordering": ["name"],
            },
        ),
    ]
