# Generated by Django 5.2.10 on 2026-01-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0004_car"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="available_seats",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="driver",
        ),
        migrations.CreateModel(
            name="RideAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_assignments",
                        to="shuttle.car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        limit_choices_to={"role": "driver"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="shuttle.ride",
                    ),
                ),
            ],
            options={
                "db_table": "ride_assignments",
                "ordering": ["created_at"],
                "unique_together": {("ride", "car"), ("ride", "driver")},
            },
        ),
    ]
