# Generated by Django 5.2.10 on 2026-01-22 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0005_remove_ride_available_seats_remove_ride_driver_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="marked_present_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_passengers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
