# Generated by Django 5.2.10 on 2026-01-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0006_reservation_marked_present_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
