# Generated by Django 5.2.10 on 2026-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0007_reservation_guest_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="rideassignment",
            name="departed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rideassignment",
            name="has_departed",
            field=models.BooleanField(default=False),
        ),
    ]
