# Generated by Django 5.2.10 on 2026-01-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0008_rideassignment_departed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="location_type",
        ),
    ]
