# Generated by Django 5.2.10 on 2026-01-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuttle", "0009_remove_location_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes",
                    models.PositiveIntegerField(help_text="Travel time in minutes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_times_to",
                        to="shuttle.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_times_from",
                        to="shuttle.location",
                    ),
                ),
            ],
            options={
                "db_table": "travel_times",
                "ordering": ["origin__name", "destination__name"],
                "unique_together": {("origin", "destination")},
            },
        ),
    ]
