# Generated by Django 5.2.11 on 2026-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0012_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_enabled', models.BooleanField(default=False)),
                ('banner_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
