# Generated by Django 5.2.11 on 2026-03-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0015_blockedperiod_ride_deleted_at_ride_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedperiod',
            name='driver',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['driver', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
