# Generated by Django 5.2.10 on 2026-01-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("shuttle", "0004_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="shuttle.car",
            ),
        ),
    ]
