# Generated by Django 5.2.10 on 2026-01-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_default_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="vehicle_info",
        ),
    ]
