# Generated by Django 5.2.10 on 2026-01-28 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_driver_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driveravailability",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["driver", "admin"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
