# Generated by Django 5.2.10 on 2026-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_allow_admin_as_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="token_expires_at",
            new_name="magic_token_expires_at",
        ),
        migrations.AddField(
            model_name="user",
            name="session_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="session_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
